feat: 🎸 Fix image load and typescript errors
kolplattformen/skolplattformen pull request #570
Opened 2021-12-01 12:01 UTC by whyer

Many small fixes:
- Fixes the image loading for Hjärntorget. Made a new api-method to fetch headers that is used from image loading component.
- No more typescript errors
- Fix warnings from test -> missing colors and brushes

2021-12-01 12:24 UTC, edenstrom requested changes

2021-12-01 12:24 UTC, edenstrom commented on libs/api-hjarntorget/lib/apiHjarntorget.ts
> +      const emitter: any = new EventEmitter()
behövs any här? kan vi typa på annat sätt?

2021-12-01 12:24 UTC, edenstrom commented on libs/api-skolplattformen/lib/features.ts
> +  LOGIN_BANK_ID_SAME_DEVICE: false,
denna key används inte längre. Bara den ovan `LOGIN_BANK_ID_SAME_DEVICE_WITHOUT_ID`.

2021-12-01 13:11 UTC, whyer commented on libs/api-hjarntorget/lib/apiHjarntorget.ts
> +      const emitter: any = new EventEmitter()
Jag lyckas inte få till någon annan typning. Jag snodde den här workarounden från Stockholms-api:t.
Tittar på det en gång till.

2021-12-01 13:12 UTC, whyer commented on libs/hooks/README.md
> +import init from '@skolplattformen/api'
Ah! Gjorde en sök och ersätt...! Den ska inte ändras

2021-12-01 13:27 UTC, whyer commented on libs/api-skolplattformen/lib/features.ts
> +  LOGIN_BANK_ID_SAME_DEVICE: false,
Fixat

2021-12-02 14:24 UTC, edenstrom approved these changes

2021-12-02 14:34 UTC, merged